### ISSUE TITLE
Is it possible to get near realtime logs 

### ISSUE THREAD

**Issue by mauricekraus** [azohra/gitrise.sh#18]
Hi, I am not really fluent in Bash, so it is difficult for me to understand the code. First of all, thanks for your hard work, works quite well so far, but is it possible to get continuous updates of the log status of Bitrise?  Or is that not possible with the Bitrise API?

The current ci log looks like the following:
Hold on... We're about to liftoff! 🚀
Build URL: https://app.bitrise.io/build/**********
Build in-progress
... 5 minutes later 
Build success
...
Complete log from Bitrise

Thanks for your help.

**Comment by aroswell** [comment]
It is possible but our early experiences with the API proved streaming unreliable. Hence, we used the conservative approach of fetching the log after the build completes. 
Is your request primarily based on an improved user experience (i.e. the feeling of following the build and knowing what going on sooner rather than later)?

**Comment by mauricekraus** [comment]
Thanks for your update, in the meantime I have looked at the code and API itself and found that it would be really problematic to use it, because it always returns the complete log (but at least structured in chunks). Yes, it is based solely on a better user experience. My current iOS testing workflow takes about 15 minutes, as it has to do a lot of unit testing and ui (Earl Grey) testing, and it's really annoying not to get feedback. I could definitely split this into two different workflows to make it run faster, but I find this very inconvenient, especially since both workflows would then represent a single fastlane. If fetching every second is generally not a good option, I would suggest a time-based fetch argument where the gitrise user could add seconds when the log should be updated (as the current status polling works). In the implementation itself, we could simply track which positions have already been seen and therefore do not need to be pushed into the output.
```
 "log_chunks": [
    {
      "chunk": "string",
      "position": 0
    }
  ],
```
If you think this is possible or a good idea, I would try to make a pull request.

**Comment by Azbagheri** [comment]
Hi @mauricekraus, 
First of all, thanks for your interest in Gitrise! We have been using Bitrise API for a while now and as @aroswell mentioned we tried streaming the logs at the beginning, but it didn’t work quite well. 
With that said, we think it’s a good idea to poll the logs in a time-based manner and it’s totally doable. However, we would want to have it as a feature that can be easily turned on and off. 

You are more than welcome to open a pull request! Please just make sure to add tests if possible. Thanks!

**Comment by Azbagheri** [comment]
Hi @mauricekraus,

We have added support for real-time logs in the latest version of Gitrise (v0.8.0)!! You can learn more about it [here](https://github.com/azohra/gitrise.sh#displaying-the-build-logs).

I'm going to close this issue. Please feel free to open a new issue if you have any questions or need help with the new features. Once again, thank you for your interest in Gitrise!
