### ISSUE TITLE
bitrise cli

### ISSUE THREAD

**Issue by henry-hz** [azohra/gitrise.sh#25]
would it be possible to run completely in Gitlab, and use the open source bitrise [cli](https://app.bitrise.io/cli) ? Maybe using a remote gitlab runner in a mac, and install the bitrise cli there ?

**Comment by Azbagheri** [comment]
hey @henry-hz, 
Not really sure if your question is related to Gitrise, but all I can say is that Gitrise and Bitrise CLI have very different use-cases. Gitrise allows you to trigger a Bitrise workflow from Gitlab and the Bitrise CLI will allow you to run (test) a Bitrise workflow locally. Therefore, if you decide to use the Bitrise CLI locally or in a Gitlab runner on a mac, you won’t need to use Gitrise at all.
