### ISSUE TITLE
Abort Bitrise build when the CI pipeline is aborted

### ISSUE THREAD

**Issue by R4md4c** [azohra/gitrise.sh#34]
Thanks a lot for this very useful script! 

I've checked the code but I couldn't find any usage of the abort [endpoint](https://devcenter.bitrise.io/api/build-trigger/#aborting-a-build). I'm wondering if it was possible to listen for a pipeline cancellation, and consequently aborts the running Bitrise build?

**Comment by Daphne-CoffeeIT** [comment]
Did you ever find a solution?

**Comment by Azbagheri** [comment]
Hey @R4md4c,

We are happy to hear Gitrise has been useful to you as well!

About this issue, it is a valid request and a nice to have, but unfortunately we won’t be supporting it as it’d be flaky. Gitrise runs on the Gitlab Runners and we don’t have insight into how gracefully runners shut down when a pipeline is cancelled and whether or not we have enough time to make a network call before then.
