### ISSUE TITLE
Triggering multiple parallel builds via gitrise script aborts the Bitrise builds

### ISSUE THREAD

**Issue by sherryleneg** [azohra/gitrise.sh#38]
Hi,

I wanted to get in touch about an issue that we are seeing when we run multiple pipelines in GitLab. We are triggering a number of  builds on ios and android via the gitrise script (between 4-6). It seems that running 2 builds in parallel works as expected, however when we trigger 3 or more the builds get aborted after a few minutes. I have tried triggering builds manually from Bitrise and didn't see any issues. I also checked our concurrency limits for our subscription and we're well under the threshold. 

I'm attaching a screenshot of the job logs from the aborted builds, there are some errors although they do not provide a lot information to go on. There aren't any build logs being generated.

Could you help please?

When I looked up these lines in the gitrise script, I saw that it's failing on the logging function
`get_build_logs()`

<img width="1507" alt="Screenshot 2023-06-16 at 00 08 22" src="https://github.com/azohra/gitrise.sh/assets/65291993/5aa0af3b-4604-4eca-82b0-d97e85f5135b">

**Comment by Azbagheri** [comment]
Hi @sherryleneg,

Sorry for our late reply. 

Looking at the date you opened the issue, the latest Gitrise version you could have used at the time is Gitrise 0.8.0 but the script in that version is only 364 lines long and doesn’t even have a line 381 where your error has occurred. It seems like you have modified the script on your side and that makes it hard for us to know what’s the issue you have run into. 

Gitrise by itself can’t abort builds.  Unless that’s a modification you’ve made on your end.  In that case, unfortunately, I won’t be able to help debug it.  However, I can provide you with some tips for better debugging in the future. 

- You can run Gitrise in the debug mode using the flag `-d` or `--debug`. This will log the API calls and store them in a folder called `gitrise_temp`. You can then use the artifacts feature of Gitlab to upload these logs to Gitlab and look through them. 
-  Use the `--stream` flag to stream the build logs. You can learn more about different ways to get build logs [here](https://github.com/Tumiya/gitrise?tab=readme-ov-file#displaying-the-build-logs)
