### ISSUE TITLE
new workflow is aborted

### ISSUE THREAD

**Issue by sun022-01** [azohra/gitrise.sh#44]
Hi guys! i have a problem using gitrise for firts time! 
i use the script with the required options and the script say "ERROR: Not Found%". I have a MAC with OS 14.1.2 (23B92) and gitrise version 0.8.1

Thx!

**Comment by Azbagheri** [comment]
Hi @sun022-01,
Thanks for your interest in Gitrise!
That error is in fact coming from Bitrise. Gitrise has made the call to Bitrise, but the project or workflow has not been found on Bitrise. Please make sure the info you're passing to Gitrise is correct. Also, make sure the access token you are using has access to your project on Bitrise.

Hope this help you!

**Comment by Azbagheri** [comment]
Closing this issue as it's resulted from passing incorrect parameters to Gitrise and no change is needed on Gitrise itself.
