### ISSUE TITLE
Build is always succeeds when --download-artifacts is used

### ISSUE THREAD

**Issue by n0vah** [azohra/gitrise.sh#52]
If I apply `--download-artifacts` to gitrise command every build is "succeeded" even if build on Bitrise is failed. Without `--download-artifacts` everything works fine - Bitrise build failed -> Gitlab job is failed, Bitrise build succeeded -> Gitlab job is succeeded.

**Example:**
```shell
gitrise -a $BITRISE_ACCESS_TOKEN -s $BITRISE_PROJECT_SLUG -w AndroidCodeCheck -b $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -e "ENVS":$ENVS --stream --download-artifacts merged-test-results.zip
```

![image](https://github.com/Tumiya/gitrise/assets/29734340/48f0c049-7d2c-44c1-8439-9dd39882e73c)

**Workaround:**
As workaround I just save build status on Bitrise to separate file, and use this build status from this file on Gitlab  as exit code.

**Comment by Azbagheri** [comment]
Hey @n0vah, thank you for opening this issue! It is fixed in the latest version of Gitrise (v0.10.0)!
